spring:
  data:
    mongodb:
      uri: mongodb+srv://rzy119:rzy1982@cluster0.b5zjast.mongodb.net/product-service
  application:
    name: product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080