eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  ## environment variables
  username: "${EUREKA_USERNAME:eureka}"
  password: "${EUREKA_PASSWORD:password}"

server:
  port: 8761

#spring:
#  security:
#    user:
#      name: eureka
#      password: password
#  application:
#    name: discovery-server